# Cultural & Venue Smart Copilot Platform - Enterprise Unified Makefile

.PHONY: help dev-backend dev-frontend test lint format mypy docker-up docker-down docker-build migrate create-migration clean check-security

help:
	@echo "========================================================================"
	@echo "    Cultural & Venue Smart Copilot Platform - Unified Commands"
	@echo "========================================================================"
	@echo "  dev-backend        - Start backend dev server locally (Port 8000)"
	@echo "  dev-frontend       - Start frontend Vite dev server locally (Port 5173)"
	@echo "  docker-up          - Start full stack dev environment (Postgres, Redis, API, Frontend, Prometheus)"
	@echo "  docker-down        - Stop and clean docker containers and volumes"
	@echo "  docker-build       - Build multi-stage dev and prod docker images"
	@echo "  test               - Run all backend unit, integration, and security tests with pytest & coverage"
	@echo "  lint               - Run Ruff and Black code checks"
	@echo "  format             - Auto-format codebase with Ruff and Black"
	@echo "  mypy               - Run strict type checking across Python codebase"
	@echo "  migrate            - Apply Alembic database migrations"
	@echo "  create-migration   - Create a new autogenerated Alembic migration (usage: make create-migration msg='desc')"
	@echo "  check-security     - Run Bandit and safety check for security vulnerabilities"
	@echo "  clean              - Clean build artifacts, pyc files, and test caches"
	@echo "========================================================================"

dev-backend:
	cd backend && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level info

dev-frontend:
	cd frontend && npm run dev

docker-up:
	docker compose -f docker-compose.yml up -d --build
	@echo "Full stack running: API http://localhost:8000/docs | Frontend http://localhost:5173"

docker-down:
	docker compose -f docker-compose.yml down -v

docker-build:
	docker compose build

test:
	cd backend && PYTHONPATH=. pytest --cov=app --cov-report=term-missing --cov-report=html -v

lint:
	cd backend && ruff check app tests
	cd frontend && npm run lint

format:
	cd backend && ruff check --fix app tests
	cd backend && black app tests

mypy:
	cd backend && mypy app

migrate:
	cd backend && alembic upgrade head

create-migration:
	@if [ -z "$(msg)" ]; then echo "Error: Provide a migration message using msg='your message'"; exit 1; fi
	cd backend && alembic revision --autogenerate -m "$(msg)"

check-security:
	cd backend && pip install bandit safety && bandit -r app/ -x tests/ && safety check

clean:
	find . -type d -name "__pycache__" -exec rm -rf {} +
	find . -type d -name ".pytest_cache" -exec rm -rf {} +
	find . -type d -name ".mypy_cache" -exec rm -rf {} +
	find . -type d -name ".ruff_cache" -exec rm -rf {} +
	rm -rf backend/htmlcov backend/.coverage frontend/dist
